In [5]:
import numpy as np
import pandas as pd

import os 
import sys

In [20]:
root_dir = os.path.dirname(os.getcwd())

order_path = os.path.join(root_dir, "data", "fct_orders.csv")
orders = pd.read_csv(order_path)

customer_path = os.path.join(root_dir, "data", "dim_customers.csv")
customers = pd.read_csv(customer_path)

product_path = os.path.join(root_dir, "data", "dim_products.csv")
products = pd.read_csv(product_path)

In [21]:
orders.head()

,brand,item_id,gross_item_value,order_date,order_datetime,product_id,order_id,customer_id
0,Brand 1,1370486,21.50,1/1/2024,2024-01-01T10:29:14,2077,1229709,5.800000e+18
1,Brand 2,3794133,4.38,1/1/2024,2024-01-01T23:30:21,119,753517,8.210000e+18
2,Brand 3,17037113,40.50,1/1/2024,2024-01-01T13:42:54.547000,5145,2994406,1.150000e+18
3,Brand 4,17037214,45.91,1/1/2024,2024-01-01T14:50:30.140000,17013,2994429,2.960000e+18
4,Brand 2,3792949,5.05,1/1/2024,2024-01-01T06:56:35,1095,753292,6.720000e+18

In [22]:
customers.head()

    customer_id country  state
0  1.270000e+18      AE  Other
1  6.690000e+18      AE  Other
2  2.320000e+18      AG  Other
3  5.340000e+18      AT  Other
4  7.700000e+18      AU  Other

In [23]:
products

      product_id product_group
0           1407         Other
1           1673         Other
2           1687         Other
3           1709         Other
4           1743         Other
...          ...           ...
3110       17677   Category 10
3111       17683   Category 10
3112       18347   Category 10
3113       20606   Category 10
3114       21872   Category 10

[3115 rows x 2 columns]